from core.constants import (
    NODE_NEWS,
    NODE_FINANCIAL,
    NODE_MARKET,
    NODE_SEC,
    NODE_MEMORY,
    NODE_QDRANT,
    NODE_AGGREGATE,
)

ALL_NODES = [
    NODE_NEWS,
    NODE_FINANCIAL,
    NODE_MARKET,
    NODE_SEC,
    NODE_QDRANT,
    NODE_MEMORY,
    NODE_AGGREGATE,
]